image: cirrusci/flutter:1.22.5

stages:
  - test
  - build

before_script:
  - flutter pub get
  - flutter clean

test:
  stage: Test
  script:
    - flutter test

  tags:
    - flutter


build:
  stage: build

#  before_script:
#    - echo "$"

  script:
    - flutter build apk

  artifacts:
    paths:
      - build/app/outputs/apk/release/app-release.apk

  tags:
    - flutter

  only:
    - tags

