image: cirrusci/flutter:1.22.5

stages:
  - Test
  - Build Android

before_script:
  - flutter pub get
  - flutter clean

test:
  stage: Test
  script:
    - flutter test

  tags:
    - flutter


build:
  stage: Build Android

  before_script:
    - touch android/key.properties
    - echo "storePassword=$STOREPASSWORD" >> android/key.properties
    - echo "keyPassword=$KEYPASSWORD" >> android/key.properties
    - echo "keyAlias=slydo" >> android/key.properties
    - echo "storeFile=slydo.jks" >> android/key.properties

  script:
    - flutter build apk

  artifacts:
    paths:
      - build/app/outputs/apk/release/app-release.apk

  tags:
    - flutter

#  only:
#    - tags

