# This file configures the analyzer, which statically analyzes Dart code to
# check for errors, warnings, and lints.
#
# The issues identified by the analyzer are surfaced in the UI of Dart-enabled
# IDEs (https://dart.dev/tools#ides-and-editors). The analyzer can also be
# invoked from the command line by running `flutter analyze`.

# The following line activates a set of recommended lints for Flutter apps,
# packages, and plugins designed to encourage good coding practices.
include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Naming conventions
    prefer_typing_uninitialized_variables: false
    always_specify_types: false
    camel_case_types: true
    camel_case_extensions: true
    lines_longer_than_80_chars: false

    # Code readability and organization
    prefer_const_constructors: true
    sort_child_properties_last: true
    unnecessary_new: true
    unnecessary_const: true
    prefer_final_fields: true
    prefer_final_locals: true

    # Code style and formatting
    prefer_expression_function_bodies: false
    prefer_void_to_null: true
    prefer_if_elements_to_conditional_expressions: true
    prefer_for_elements_to_map_fromIterable: true

    type_annotate_public_apis: true
    always_declare_return_types: true
    avoid_print: true
