name: Slydo
description: The slydo application.
version: 1.1.6+37

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
#  intl_translation: ^0.17.10+1

  hive: ^2.2.3
  http: ^0.13.5
  get_it: ^7.2.0
  lottie: ^1.3.0
  shimmer: ^2.0.0
  provider: ^6.0.1
  sqflite: ^2.0.0+4
  open_file: ^3.2.1
  readmore: ^2.2.0
  equatable: ^2.0.3
  hive_flutter: ^1.1.0
  flutter_svg: ^1.0.3
  validators: ^3.0.0
  get_storage: ^2.0.3
#  ext_storage: ^1.0.3
  flutter_quill: ^6.0.9
  path_provider: ^2.0.5
  textfield_tags: 1.4.3
  external_path: ^1.0.1
  qr_code_scanner: ^1.0.1
  dropdown_button2: ^1.4.0
  flutter_linkify: ^5.0.2
  flutter_colorpicker: ^1.0.3
  flutter_downloader: ^1.7.4
  page_view_indicators: ^2.0.0
  image_picker: ^0.8.4+2
#  downloads_path_provider_28: ^0.1.2
  firebase_crashlytics: ^3.0.3
  firebase_messaging: ^14.0.3
  cached_network_image: ^3.1.0
  shared_preferences: ^2.0.8
  passcode_screen: ^2.0.0
  location: 4.4.0
  flutter_slidable: ^0.6.0
  device_info: ^2.0.2
  pull_to_refresh: ^2.0.0
  connectivity: ^3.0.6
  uuid: ^3.0.4
  intl: ^0.17.0
  flutter_staggered_grid_view: ^0.4.0
  package_info: ^2.0.2
  maps_launcher: ^2.0.1
  devicelocale: ^0.4.3
  flip_card: ^0.5.0
  url_launcher: 6.1.4
  animated_fractionally_sized_box: ^2.0.1
  custom_qr_generator: ^0.1.0
  modal_progress_hud_nsn: ^0.3.0
  # Adding this logger for easy debuggin
  logger: ^1.1.0
#  charts_flutter: ^0.11.0
  charts_flutter:
    git:
      url: https://github.com/google/charts.git
      path: charts_flutter
      ref: 30477090290b348ed3101bc13017aae465f59017
#  flutter_link_preview:
#    git:
#      url: https://github.com/ItzNotABug/flutter_link_preview'
#      ref: fe0d3db907604f0d4d3d825aa69b82d99621f776
  badges: ^2.0.1
  flutter_credit_card: ^3.0.0
  share: ^2.0.4
  carousel_slider: ^4.0.0
  page_transition: ^2.0.4
  pinput: ^1.2.0
  printing: ^5.6.0
  pdf: ^3.6.1
  video_player: ^2.4.0
  wakelock: ^0.5.6
  percent_indicator: ^3.0.1
  assets_audio_player: ^3.0.5
  video_thumbnail: ^0.5.0
  flutter_video_info: ^1.2.0
  quiver: ^3.0.1
  camera: 0.9.4+1
  package_info_plus: ^1.4.0
  web_socket_channel: ^2.1.0
  photo_view: ^0.14.0
  flutter_keyboard_visibility: ^5.0.3
  crypto: ^3.0.1
  file_picker: ^4.1.2
  flutter_sound: ^8.4.2
  flare_flutter: ^3.0.2
  lazy_load_scrollview: ^1.3.0
  permission_handler: ^10.2.0
  shake: ^1.0.1
  sizer: ^2.0.15
  colorful_safe_area: ^0.3.0
  flutter_secure_storage: ^4.2.1
  image_cropper: ^3.0.0
  linkwell: ^2.0.6
  swipe_to: ^0.1.0-nullsafety.1
  giphy_picker: ^2.0.0
  awesome_notifications: ^0.6.19
  flutter_local_notifications: ^8.2.0
  sqflite_migration: ^0.3.0
#  flutter_windowmanager: ^0.2.0
  flutter_map: ^0.14.0
  google_maps_flutter: ^2.0.10
  flutter_polyline_points: ^1.0.0
  extended_text_field: ^8.0.0
  workmanager: 0.5.1
  receive_sharing_intent: ^1.4.5
  rxdart: ^0.27.3
  progress_indicators: ^1.0.0
  fluttertoast: ^8.0.8
  fast_gbk: ^1.0.0
#  coachmaker: ^0.1.1
  tutorial_coach_mark: ^1.1.1
  syncfusion_flutter_pdf: ^19.3.47-beta
  flutter_rating_bar: ^4.0.0
  currency_text_input_formatter: ^2.1.5
  video_trimmer: 1.1.3
  # video_editor: ^1.3.0
  ffmpeg_kit_flutter: ^4.5.1
  flutter_speed_dial: ^6.2.0


#dependency_overrides:
#  intl: ^0.16.1
#  http: ^0.12.0+2
  collection: ^1.15.0-nullsafety.4
  webview_flutter: ^3.0.4
  images_picker: ^1.2.11
  cupertino_icons: ^1.0.5

flutter_icons:
  android: "launcher_icon"
  image_path_ios: "assets/images/appIcon/appIcon_IOS.png"
  image_path_android: "assets/images/appIcon/appIcon_IOS.png"
  ios: true

dependency_validator:
  # Exclude one or more paths from being scanned. Supports glob syntax.
  exclude:
    - "app/**"
  # Ignore one or more packages.
  ignore:
    - intl

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2
#  mockito: ^4.1.3

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font isc
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/splash/
    - assets/images/default_image/
    - assets/images/flags/
    - assets/images/category/
    - assets/images/intro_images/
    - assets/images/envelope/
    - assets/images/flare/
    - assets/fonts/
    - assets/lottie/
    - assets/images/appIcon/
    - assets/images/ask/
    - assets/images/no_result_found_2.png
    - assets/sounds/
    - assets/images/utility/
    - assets/images/taxi/
    - assets/images/yarn/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: CircularStd
      fonts:
        - asset: assets/fonts/CircularStd-Medium.otf
        - asset: assets/fonts/CircularStd-Bold.otf
          weight: 700

    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
        - asset: assets/fonts/OpenSans-Light.ttf
          weight: 300
        - asset: assets/fonts/OpenSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/OpenSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/OpenSans-ExtraBold.ttf
          weight: 800

    - family:  SlydoAppIcon
      fonts:
        - asset: assets/fonts/SlydoAppIcon.ttf

    - family: SlydoAppIconNew
      fonts:
        - asset: assets/fonts/SlydoAppIconNew.ttf

  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
