name: Slydo
description: The slydo application.
version: 2.2.2+65

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  animated_bottom_navigation_bar: ^1.3.3
  assets_audio_player: ^3.1.1
  awesome_notifications: ^0.9.3+1
  badges: 3.1.2
  cached_network_image: 3.3.1
  cached_video_player_plus: ^3.0.1
  camera: ^0.11.0+1
  carousel_slider: 4.2.1
  charts_flutter:
    git:
      url: https://github.com/google/charts.git
      path: charts_flutter
      ref: 30477090290b348ed3101bc13017aae465f59017
  colorful_safe_area: ^1.0.0
  connectivity_plus: ^6.0.3
  currency_text_input_formatter: 2.2.3
  custom_qr_generator: ^0.1.2
  device_info_plus: ^10.1.0
  devicelocale: ^0.7.1
  disk_space: ^0.2.1
  dropdown_button2: ^2.3.9
  equatable: ^2.0.5
  external_path: ^1.0.3
  fast_gbk: ^1.0.0
  file_picker: ^8.0.3
  firebase_crashlytics: ^4.0.0
  firebase_messaging: ^15.0.0
  flare_flutter: ^3.0.2
  flip_card: ^0.7.0
  flutter:
    sdk: flutter
  flutter_credit_card: ^4.0.1
  flutter_dialogs: ^3.0.0
  flutter_downloader: ^1.11.7
  flutter_local_notifications: ^17.1.2
  flutter_map: ^7.0.0
  flutter_quill_extensions: ^9.3.21
  flutter_rating_bar: ^4.0.1
  flutter_secure_storage: ^9.2.2
  flutter_slidable: ^3.1.0
  flutter_speed_dial: ^7.0.0
  flutter_spinkit: ^5.2.1
  flutter_staggered_grid_view: ^0.7.0
  flutter_svg: ^1.0.0
  flutter_video_info: ^1.3.2
  fluttertoast: ^8.2.6
  get_it: ^7.7.0
  get_storage: ^2.1.1
  giphy_picker: ^3.0.2
  google_maps_flutter: ^2.6.1
  hash_at_links_detector: ^1.0.1
  image_picker: ^1.0.4
  intl: ^0.19.0
  lazy_load_scrollview: ^1.3.0
  like_button: ^2.0.5
  linkwell: ^2.0.6
  location: ^6.0.2
  lottie: ^3.1.2
  maps_launcher: ^2.2.1
  modal_progress_hud_nsn: ^0.5.1
  neat_periodic_task: ^2.0.1
  open_filex: ^4.4.0
  package_info_plus: ^8.0.0
  page_transition: ^2.1.0
  page_view_indicators: ^2.0.0
  passcode_screen: ^2.0.1
  pdf: ^3.10.8
  percent_indicator: ^4.2.3
  permission_handler: ^11.3.1
  pinput: ^4.0.0
  printing: ^5.12.0
  progress_indicators: ^1.0.0
  provider: ^6.1.2
  pull_to_refresh: ^2.0.0
  qr_code_scanner: ^1.0.1
  receive_sharing_intent: ^1.8.0
  screenshot: ^3.0.0
  shake: ^2.2.0
  share_plus: ^9.0.0
  shared_preferences: ^2.2.3
  shimmer: ^3.0.0
  sizer: ^2.0.15
  sqflite_migration: ^0.3.0
  story_view: ^0.16.5
  swipe_image_gallery: ^0.8.7
  swipe_to: ^1.0.6
  textfield_tags: 2.0.2
  tutorial_coach_mark: ^1.2.11
  video_thumbnail: ^0.5.3
  video_trimmer: ^3.0.1
  wakelock: ^0.6.2
  web_socket_channel: ^3.0.0
  webview_flutter: ^4.8.0
  text_scroll: ^0.2.0
  dropdown_search: ^5.0.6
  image_cropper: ^6.0.0
  git_hooks: ^1.0.1
  app_links: ^6.1.1
  jumping_dot: ^0.0.6
  video_player: ^2.8.6
  geolocator: ^12.0.0
  photo_view: ^0.14.0
  flutter_masked_text2: ^0.9.1
  gallery_saver: ^2.3.2
  flutter_sound: ^9.6.0

dependency_overrides:
  js: ^0.7.1
  uuid: ^4.4.0
  wakelock_windows: ^0.2.1
  win32: ^5.5.1
  intl: ^0.17.0
  http: ^1.2.1

flutter_icons:
  android: "launcher_icon"
  image_path_ios: "assets/images/appIcon/appIcon_IOS.png"
  image_path_android: "assets/images/appIcon/appIcon_IOS.png"
  ios: true

#dependency_validator:
#  # Exclude one or more paths from being scanned. Supports glob syntax.
#  exclude:
#    - "app/**"
#  # Ignore one or more packages.
#  ignore:
#    - intl

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
#  mockito: ^4.1.3
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font isc
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/splash/
    - assets/images/default_image/
    - assets/images/flags/
    - assets/images/category/
    - assets/images/intro_images/
    - assets/images/envelope/
    - assets/images/flare/
    - assets/fonts/
    - assets/lottie/
    - assets/images/appIcon/
    - assets/images/ask/
    - assets/images/no_result_found_2.png
    - assets/sounds/
    - assets/images/utility/
    - assets/images/taxi/
    - assets/images/yarn/
    - assets/images/payout/
    - assets/images/store/
    - assets/images/home/
    - assets/images/rider/
    - assets/map_style.json

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: CircularStd
      fonts:
        - asset: assets/fonts/CircularStd-Medium.otf
        - asset: assets/fonts/CircularStd-Bold.otf
          weight: 700

    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
        - asset: assets/fonts/OpenSans-Light.ttf
          weight: 300
        - asset: assets/fonts/OpenSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/OpenSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/OpenSans-ExtraBold.ttf
          weight: 800

    - family: SlydoAppIcon
      fonts:
        - asset: assets/fonts/SlydoAppIcon.ttf

    - family: SlydoAppIconNew
      fonts:
        - asset: assets/fonts/SlydoAppIconNew.ttf

    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Bold.ttf
        - asset: assets/fonts/Inter-Light.ttf
          weight: 300
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter-ExtraBold.ttf
          weight: 800
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
