/// Flutter icons SlydoAppIconNew
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  SlydoAppIconNew
///      fonts:
///       - asset: fonts/SlydoAppIconNew.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class SlydoAppIconNew {
  SlydoAppIconNew._();

  static const _kFontFam = 'SlydoAppIconNew';
  static const String? _kFontPkg = null;

  static const IconData vector = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData scan = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cart = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData message = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData send = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bag = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData play = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData explore = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
