/// Flutter icons SlydoAppIcon
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  SlydoAppIcon
///      fonts:
///       - asset: fonts/SlydoAppIcon.ttf
///
///
/// * Font Awesome 4, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
/// * Entypo, Copyright (C) 2012 by Daniel Bruce
///         Author:    Daniel Bruce
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.entypo.com
///
library;

import 'package:flutter/widgets.dart';

class SlydoAppIcon {
  SlydoAppIcon._();

  static const _kFontFam = 'SlydoAppIcon';
  static const _mFontFam = 'MaterialIcons';
  static const String? _kFontPkg = null;

  static const IconData naira =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eyeClose =
      IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData qrCode =
      IconData(0xf00cc, fontFamily: _mFontFam, fontPackage: _kFontPkg);
  static const IconData payout =
      IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData payoutList =
      IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData circleUser =
      IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData location =
      IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData connections =
      IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData addImage =
      IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData date =
      IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData image =
      IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData leave =
      IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData message =
      IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData menu =
      IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData note =
      IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData note_2 =
      IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData settings =
      IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home =
      IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eye =
      IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user =
      IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData transactions =
      IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bank =
      IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData translation =
      IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData product =
      IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData addCart =
      IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData store =
      IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cart =
      IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData send =
      IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search =
      IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData share =
      IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData receive =
      IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData add =
      IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData remove =
      IconData(0xe820, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData textMessage =
      IconData(0xe821, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData block =
      IconData(0xe822, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData checked =
      IconData(0xe823, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData plus =
      IconData(0xe824, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData minus =
      IconData(0xe825, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData star =
      IconData(0xe826, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData graph =
      IconData(0xe827, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData category =
      IconData(0xe828, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData noteFilled =
      IconData(0xe829, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData trueIcon =
      IconData(0xe82a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData unarchive =
      IconData(0xe82b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData edit =
      IconData(0xe82c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData archive =
      IconData(0xe82d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData removeConnection =
      IconData(0xe82e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData falseIcon =
      IconData(0xe82f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sendConnectionRequest =
      IconData(0xe830, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cancelConnectionRequest =
      IconData(0xe831, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData unblock =
      IconData(0xe832, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData delete =
      IconData(0xe833, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lineGraph =
      IconData(0xe834, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData generalCategory =
      IconData(0xe835, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gorceriesCategory =
      IconData(0xe836, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData financesCategory =
      IconData(0xe837, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData personalCareCategory =
      IconData(0xe838, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData holidaysCategory =
      IconData(0xe839, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData familyCategory =
      IconData(0xe83a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData expensesCategory =
      IconData(0xe83b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData giftsCategory =
      IconData(0xe83c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData entertainmentCategory =
      IconData(0xe83d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eatingoutCategory =
      IconData(0xe83e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData charityCategory =
      IconData(0xe83f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData billsCategory =
      IconData(0xe840, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData transportCategory =
      IconData(0xe841, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shoppingCategory =
      IconData(0xe842, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData trainMoreApps =
      IconData(0xe843, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wealthMoreApps =
      IconData(0xe844, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData flightMoreApps =
      IconData(0xe845, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData more =
      IconData(0xe846, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData propertyMoreApps =
      IconData(0xe847, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eventsMoreApps =
      IconData(0xe848, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData newsMoreApps =
      IconData(0xe849, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hotelsMoreApps =
      IconData(0xe84a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData musicMoreApps =
      IconData(0xe84b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData moviesMoreApps =
      IconData(0xe84c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData filter =
      IconData(0xe84d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData videoPlay =
      IconData(0xe84e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData heartEmpty =
      IconData(0xe84f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData heart_1 =
      IconData(0xe850, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData forward_10 =
      IconData(0xe851, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fullScreen =
      IconData(0xe852, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData rewind_10 =
      IconData(0xe853, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ccw =
      IconData(0xe854, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cw =
      IconData(0xe855, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData locationCircle =
      IconData(0xe856, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData priceTag =
      IconData(0xe857, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData seat =
      IconData(0xe858, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gate =
      IconData(0xe859, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData swap =
      IconData(0xe85a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData freeWifi =
      IconData(0xe85b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData washer =
      IconData(0xe85c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData garden =
      IconData(0xe85d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fire =
      IconData(0xe85e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData achievement =
      IconData(0xe85f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData kitchen =
      IconData(0xe860, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tv =
      IconData(0xe861, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bathroom =
      IconData(0xe862, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData partner =
      IconData(0xe863, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData musicPlay =
      IconData(0xe864, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData musicPlay1 =
      IconData(0xe865, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData musicBack =
      IconData(0xe866, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData musicNext =
      IconData(0xe867, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData musicRepeat =
      IconData(0xe868, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData musicSuffle =
      IconData(0xe869, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bedroom =
      IconData(0xe86a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData couch =
      IconData(0xe86b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData toilet =
      IconData(0xe86c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sendMessage =
      IconData(0xe86d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sendMessage2 =
      IconData(0xe86e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mic =
      IconData(0xe86f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData close_2 =
      IconData(0xe870, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData reply =
      IconData(0xe871, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData copy =
      IconData(0xe872, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData makeAdmin =
      IconData(0xe873, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData removeAdmin =
      IconData(0xe874, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mute =
      IconData(0xe875, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData unmute =
      IconData(0xe876, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData clock =
      IconData(0xe877, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData subscriptionStatus =
      IconData(0xe878, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData utilityAirtime =
      IconData(0xe879, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData utilityBetting =
      IconData(0xe87a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData utilityElectricity =
      IconData(0xe87b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData utilityHistory =
      IconData(0xe87c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData utilitySvg =
      IconData(0xe87d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData utilityTax =
      IconData(0xe87e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData utilityToll =
      IconData(0xe87f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData utility =
      IconData(0xe880, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData myLocation =
      IconData(0xe881, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData taxiCall =
      IconData(0xe882, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData locationPin =
      IconData(0xe883, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData taxiMsg =
      IconData(0xe884, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData services =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData deliveryDining =
      IconData(0xe1bd, fontFamily: _mFontFam, fontPackage: _kFontPkg);
  static const IconData addGroup =
      IconData(0xe2ec, fontFamily: _mFontFam, fontPackage: _kFontPkg);
  static const IconData addChannel =
      IconData(0xebc9, fontFamily: _mFontFam, fontPackage: _kFontPkg);
}
