/// Flutter icons SlydoAppIconNew
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  SlydoAppIconNew
///      fonts:
///       - asset: fonts/SlydoAppIconNew.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class SlydoAppIconNew {
  SlydoAppIconNew._();

  static const _kFontFam = 'SlydoAppIconNew';
  static const String? _kFontPkg = null;

  static const IconData vector_1 = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData edit_post = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData delete_post = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dashboard_chat = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData moment = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData profile = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dashboard_yarn = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData notification = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData filter = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData question = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData yarn = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bounty = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData save_post = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hide_post = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData super_store = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hide_commenting = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData explore = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chat = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData moment_1 = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData inbox = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cart = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
