/// Flutter icons SlydoAppIcon
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  SlydoAppIcon
///      fonts:
///       - asset: fonts/SlydoAppIcon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class SlydoAppIcon {
  SlydoAppIcon._();

  static const _kFontFam = 'SlydoAppIcon';
  static const _kFontPkg = null;

  static const IconData naira = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eye_close = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData qr_code = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData payout = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData payout_list = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData circle_user = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData location = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData connections = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData add_image = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData date = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData image = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData leave = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData message = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData menu = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData note = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData note_2 = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData settings = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eye = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData transactions = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bank = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData translation = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData product = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData add_cart = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData store = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cart = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData send = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search = IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData share = IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData receive = IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData add = IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
